version: '2'
services:
   cassandra:
    image: cassandra:3
    container_name: cassandra
    ports:
     - 9042:9042
     - 7199:7199
   environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
   restart: always
   volumes:
      - ./out/cassandra_data:/var/lib/cassandra